--- #YAML:1.0
name:               Win32-Process-Critical
version:            1.023
abstract:           Prevent interupt by setting your program as critical progress
author:
    - Baggio, Kwok Lok Chung <RootKwok@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
